use ReadRealm

IF (EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_Name = 'BookUsers'))
BEGIN
	IF (EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'UserId' AND Object_ID = Object_ID(N'BookUsers')))
	BEGIN
		ALTER TABLE BookUsers
		DROP CONSTRAINT PK_BookUser_BookId_UserId

		ALTER TABLE BookUsers
		ALTER COLUMN UserId VARCHAR(50) NOT NULL

		ALTER TABLE BookUsers
		ADD CONSTRAINT PK_BookUser_BookId_UserId PRIMARY KEY (BookId, UserId)
	END
END

IF (EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_Name = 'Notes'))
BEGIN
	IF (EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'UserId' AND Object_ID = Object_ID(N'Notes')))
	BEGIN
		ALTER TABLE Notes
		DROP CONSTRAINT PK_Note_BookId_UserId_Chapter_DatePosted

		ALTER TABLE Notes
		ALTER COLUMN UserId VARCHAR(50) NOT NULL

		ALTER TABLE Notes
		ADD CONSTRAINT PK_Note_BookId_UserId_Chapter_DatePosted PRIMARY KEY (BookId, UserId, Chapter, DatePosted)
	END
END

IF (EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_Name = 'Friends'))
BEGIN
	IF (EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='PK_Friend_FirstUserId_SecondUserId'))
	BEGIN
		ALTER TABLE Friends
		DROP CONSTRAINT PK_Friend_FirstUserId_SecondUserId
	END

	IF (EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'FirstUserId' AND Object_ID = Object_ID(N'Friends')))
	BEGIN
		ALTER TABLE Friends
		ALTER COLUMN FirstUserId VARCHAR(50) NOT NULL
	END
	IF (EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'SecondUserId' AND Object_ID = Object_ID(N'Friends')))
	BEGIN
		ALTER TABLE Friends
		ALTER COLUMN SecondUserId VARCHAR(50) NOT NULL
	END
	
	IF (NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='PK_Friend_FirstUserId_SecondUserId'))
	BEGIN
		ALTER TABLE Friends
		ADD CONSTRAINT PK_Friend_FirstUserId_SecondUserId PRIMARY KEY (FirstUserId, SecondUserId)
	END

	IF (NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='Check_Friend_FirstUserId_SecondUserId'))
	BEGIN
		ALTER TABLE Friends
		ADD CONSTRAINT Check_Friend_FirstUserId_SecondUserId CHECK (FirstUserId <> SecondUserId)
	END
END