// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadRealmBackend.Models.Entities;

public partial class BookUser
{
    public int BookId { get; set; }

    public string UserId { get; set; }

    public int CurrentChapter { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public decimal? Rating { get; set; }

    public int? StatusId { get; set; }

    public virtual Book Book { get; set; }

    public virtual Status Status { get; set; }
}