// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadRealmBackend.Models.Entities;

public partial class FriendRequest
{
    public string SenderUserId { get; set; }

    public string ReceiverUserId { get; set; }
}