// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadRealmBackend.Models.Entities;

public partial class Note
{
    public string UserId { get; set; }

    public int BookId { get; set; }

    public int Chapter { get; set; }

    public DateOnly DatePosted { get; set; }

    public string Text { get; set; }

    public int Private { get; set; }

    public int? TypeId { get; set; }

    public virtual Book Book { get; set; }

    public virtual NoteType Type { get; set; }
}